[package]
name = "puzzle_01"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.12.2"
thiserror = "2.0.17"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
